<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="keywords" content="personal​ page, elvira piatkina, javascript developer">
    <meta name="author" content="Elvira Piatkina">
    <meta name="description" content="Personal​ page Elvira Piatkina">
    <meta name="robots" content="index, follow">
	<title>Personal Page</title>
	<link rel="stylesheet" href="reset.css">
	<link rel="stylesheet" href="main.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>
</head>
<body>

	<div class="main">

		<header>
			<div class="top_header">
				<div class="photo">
						<img src="elvira_piatkina.jpg">
				</div>
				<div class="container">
					<div class="contacts">
						<a href="tel:+380 (96) 981 81 24">
							<i class="fas fa-mobile-alt"></i>
							+380 (96) 981 81 24
						</a>
					</div>
					<div class="contacts">
						<a href="mailto:elvira.piatkina@gmail.com">
							<i class="fas fa-at"></i>
							elvira.piatkina@gmail.com
						</a>
					</div>
					<div class="contacts">
						<a href="#">
							<i class="far fa-envelope"></i>
							Kordybu str.,7, Lviv, Ukraine
						</a>
					</div>
				</div>
				<div class="name">
					<p>ELVIRA PIATKINA</p>
				</div>
				<div class="position">
					<p>Junior Front-End Developer</p>
				</div>
			</div>
		</header>

		<div class="wrap_skills">
			<div class="wrap_skills_grid">
				<div class="personal_skills">
					<p>PERSONAL SKILLS</p>
				</div>
				<div class="skills_container">
					<div class="skill">
						<p>CSS</p>
						<div class="skill_line">
							<div class="skill_line_persent90"></div>
						</div>
					</div>
					<div class="skill">
						<p>C++</p>
						<div class="skill_line">
							<div class="skill_line_persent90"></div>
						</div>
					</div>
					<div class="skill">
						<p>Java</p>
						<div class="skill_line">
							<div class="skill_line_persent90"></div>
						</div>
					</div>
				</div>
				<div class="skills_container">
					<div class="skill">
						<p>JS</p>
						<div class="skill_line">
							<div class="skill_line_persent70"></div>
						</div>
					</div>
					<div class="skill">
						<p>Pyton</p>
						<div class="skill_line">
							<div class="skill_line_persent70"></div>
						</div>
					</div>
					<div class="skill">
						<p>Go</p>
						<div class="skill_line">
							<div class="skill_line_persent45"></div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="wrap_education">
			<div class="wrap_ed">
				<p>EDUCATION</p>

				<div class="education">
					<p>ACADEMIC EDUCATION</p>
					<p>(09/2008 - 02/2014)</p>
					<p>Simon  Kuznets Kharkiv National University of Economics, Kharkiv, Ukraine</p>
					<p>Master's degree in Accounting and Audit</p>
				</div>

				<div class="education">
					<p>EDUCATION / PRACTISE</p>
					<p>(01/2018 - 04/2018)</p>
					<p>SkillUp, Lviv, Ukraine</p>
					<p>BASIC WEB AND SQL FOR SOFTWARE TESTING course & FRONT-END course</p>
				</div>
			</div>
		</div>

		<div class="wrap_education wrap_education_bgc">
			<div class="wrap_ed">
				<p>EXPERIENCE</p>

				<div class="education">
					<p>Anheuser-Busch InBev, Kharkiv, Ukraine</p>
					<p>Fixed Assets Specialist (04/2014 - 01/2018)</p>
					<p>Technologies/Tools: VBA (Visual Basic for Applications), MS Excel Advanced, SAP, Sales Work.</p>
					<ul>
						<li>Conducting the VBA (Visual Basic for Applications) courses for colleagues. More than 30 employees have been trained;</li>
						<li>Automating of routine processes of macro process (creating macros in VBA  for Excel, Outlook, SAP);</li>
						<li>Timely and correct control of fixed assets (FA) accounting (production, commercial, IT equipment, intangible assets) in SAP system.</li>
						<li>Regional team leader. Work in a team, focused on the result:</li>
							<ul>
								<li>1 FTE has been reduced by automating and streamlining of regional operations;</li>
								<li>Reduction of losses of commercial equipment from 14% to 2%.</li>
							</ul>
					</ul>
				</div>
			</div>
		</div>

		<div class="wrap_interests">
			<div class="wrap_inter">
				<div class="personal_skills">
					<p>INTERESTS</p>
				</div>

				<div class="interests_container">
					<div class="interest">
						<p>LITERATURE</p>
					</div>
					<div class="interest">
						<p>POETRY</p>
					</div>
					<div class="interest">
						<p>PROGRAMMING</p>
					</div>
					<div class="interest">
						<p>TRAVELLING</p>
					</div>
				</div>

				<div class="interests_container">
					<div class="interest">
						<p>INTERNET</p>
					</div>
					<div class="interest">
						<p>RUNNING</p>
					</div>
					<div class="interest">
						<p>READING</p>
					</div>
					<div class="interest">
						<p>SHOPPIHG</p>
					</div>
				</div>
			</div>
		</div>

		<div class="wrap_languages">
			<div class="wrap_lang">
				<div class="personal_skills">
					<p>languages</p>
				</div>

				<div class="lang_container">
					<div class="lang">
						<p>English</p>
						<div>
							<i class="fas fa-star"></i>
							<i class="fas fa-star"></i>
							<i class="fas fa-star"></i>
							<i class="far fa-star"></i>
							<i class="far fa-star"></i>
						</div>
					</div>
					<div class="lang">
						<p>Ukrainian</p>
						<div>
							<i class="fas fa-star"></i>
							<i class="fas fa-star"></i>
							<i class="fas fa-star"></i>
							<i class="fas fa-star"></i>
							<i class="fas fa-star"></i>
						</div>
					</div>
					<div class="lang">
						<p>Hebrew</p>
						<div>
							<i class="fas fa-star-of-david"></i>
							<i class="fas fa-star-of-david"></i>
							<i class="fas fa-star-of-david"></i>
							<i class="fas fa-star-of-david"></i>
							<i class="fas fa-star-of-david"></i>
						</div>
					</div>
					<div class="lang">
						<p>Turkish</p>
						<div>
							<i class="fas fa-star-and-crescent"></i>
							<i class="fas fa-star-and-crescent"></i>
							<i class="fas fa-star-and-crescent"></i>
							<i class="fas fa-star-and-crescent"></i>
							<i class="fas fa-star-and-crescent"></i>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="services">
			<div class="personal_skills">
					<p>my offers</p>
			</div>
			<div class="services_flexblok">
				<div class="service_flexbox">
					<div><img src="pe-7s-diamond.png"></div>
					<div>ui / ux design</div>
					<div>Development of a unique design on request</div>
				</div>
				<div class="service_flexbox">
					<div><img src="pe-7s-arc.png"></div>
					<div>web development</div>
					<div>Development according to yuors requirements</div>
				</div>
				<div class="service_flexbox">
					<div><img src="pe-7s-phone.png"></div>
					<div>app / mobile</div>
					<div>Mobile development and adaptation</div>
				</div>
				<div class="service_flexbox">
					<div><img src="pe-7s-joy.png"></div>
					<div>game design</div>
					<div>Character drawing and much more</div>
				</div>
				<div class="service_flexbox">
					<div><img src="pe-7s-plane.png"></div>
					<div>SEO / marketing</div>
					<div>I will make sure your site is top search</div>
				</div>
				<div class="service_flexbox">
					<div><img src="pe-7s-star.png"></div>
					<div>photography</div>
					<div>Only the best graphics will fill your app</div>
				</div>
				<div class="service_flexbox">
					<div><img src="pe-7s-magic-wand.png"></div>
					<div>graphic design</div>
					<div>It is an important part of the app, and I will do it perfectly</div>
				</div>
				<div class="service_flexbox">
					<div><img src="pe-7s-paint-bucket.png"></div>
					<div>illustrations</div>
					<div>At your request I will draw illustrations of any complexity.</div>
				</div>
			</div>
		</div>

		<div class="need_project">
			<div class="need_project_text">
				<p>Need a Project?  I can help You!</p>
				<p>Let me know what you're looking for. I will take a look and see if this could be the start of something beautiful.</p>
			</div>
			<div class="need_project_form" id="npf">
				<form name="new_project" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">
					<p><input type="text" id="npf" name="name" placeholder="Your Name" required></p>
					<p><input type="text" id="npf" name="email" placeholder="Your Email" required></p>
					<p><input type="text" id="npf" name="title" placeholder="Your Title" required></p>
					<p><textarea id="npf" name="comment" placeholder="Your Comment" cols="60" rows="8" required></textarea></p>
					<p>
						<?php
							if(!empty($error)):
								echo $error;
							else:
								echo $success;
							endif;
						?>
					</p>
					<p><input type="submit" class="submit" id="npf" name="submit" value="send message"></p>

				</form>
			</div>
		</div>

	</div>

</body>
</html>